### ISSUE TITLE
Sequences Diagrams of last week should be updated

### ISSUE THREAD

**Issue by fahricansanli** [bounswe/bounswe2019group10#30]
Sequence diagrams created and added last week are a little bit simple and do not cover enough functionality of our project. So, let's update them. 
Assignees can check the last year's and this year's repositories.

**Comment by fahricansanli** [comment]
Update user diagram and add Language diagram are updated.

**Comment by uskudarli** [comment]
It is better to assign specific parts of the task to individuals so that you can track the progress. 

If one person starts it is "in progress". If others don't do anything what is the "status"? Technically "in progress" you may say. But in practice you can benefit from more tight definition of tasks. 

Also, who reviews ?
